openapi: 3.0.0

info:
  title: SIMBAD-PIPELINE REST API
  version: v1
  contact:
    email: jakub.sokolowski1996@gmai.com

tags:
  - name: SIMBAD-PIPELINE

servers:
  - url: /api/simulation

paths:
  /api/simulation/status:
    get:
      tags:
        - STATUS
      operationId: getSimulationStatus
      description: Get SimulationStatus
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationStatus"
  /api/simulation/latest:
    get:
      tags:
        - STATUS
      operationId: getLatestSimulation
      description: Get latest stimulation data
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationInfo"
  /api/simulation/start:
    post:
      tags:
        - SIMULATION
      operationId: startSimulation
      description: Starts simulation process
      requestBody:
        content:
          application:/json:
            schema:
              $ref: "#/components/schemas/StartSimulationRequest"
      responses:
        "202":
          description: Request is accepted and command starts to execute
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationStepInfo"
        "400":
          description: Simulation process is already running
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationError"
  /api/simulation/status/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
    get:
      tags:
        - STATUS
      summary: Get all info of simulation specified by id
      operationId: getSimulationInfo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationInfo"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationError"
  /api/simulation/step/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
    get:
      tags:
        - STATUS
      summary: Get all info of simulation step specified by id
      operationId: getSimulationStepInfo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationStepInfo"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationError"
  /api/simulation/range/latest:
    get:
      tags:
        - STATUS
      operationId: getLatestSimulations
      description: Get n latest simulation id
      requestBody:
        content:
          application:/json:
            schema:
              $ref: "#/components/schemas/SimulationRangeRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/SimulationSimpleInfo"
  /api/simulation/range/chunk:
    get:
      tags:
        - STATUS
      operationId: getSimulationsAfterId
      description: Get n latest simulation after speific id
      requestBody:
        content:
          application:/json:
            schema:
              $ref: "#/components/schemas/SimulationRangeRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/SimulationSimpleInfo"

  /api/artifact/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - STATUS
      summary: Get all info of artifact specified by id
      operationId: getArtifactInfo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArtifactInfo"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationError"
  /api/artifact/{id}/download:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
    get:
      tags:
        - STATUS
      summary: Download artifact
      operationId: downloadArtifact
      responses:
        "200":
          description: OK
          content:
            application/*:
              schema:
                type: string
                format: binary
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationError"

components:
  schemas:
    StartSimulationRequest:
      type: object
      properties:
        configurationName:
          description: The configuration file name
          type: string
        configuration:
          description: The configuration file to be sent to CLI
          type: string
          format: binary
      required:
        - configuration
        - configurationName
    StartSimulationResponse:
      type: object
      properties:
        simulationId:
          type: number
          description: The id of started simulation
        simulationStep:
          type: object
          description: The first step of started simuation
          $ref: '#/components/schemas/SimulationStepInfo'
    SimulationError:
      type: object
      properties:
        cause:
          description: The cause of an error
          type: string
    SimulationStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - BUSY
            - IDLE
          description: Simulation status - BUSY / IDLE
        currentStep:
          type: string
          enum:
            - CONF
            - CLI
            - ANALYZER
            - REPORT
            - FINISHED
          description: Current step of simulation pipeline
        simulationId:
          type: number
          description: The id of simulation
      example:
        status: BUSY
        currentStep: CLI
        simulationId: 123
    ArtifactInfo:
      type: object
      required:
        - id
        - simulationId
        - stepId
        - createdUtc
        - sizeKb
        - name
        - path
        - fileType
      properties:
        id:
          type: number
          description: The id of artifact
        simulationId:
          type: number
          description: The id of simulation in which the artifact was created
        stepId:
          type: number
          description: The id of step in which the artifact was created
        createdUtc:
          type: string
          description: UTC timestamp when artifact was created
        sizeKb:
          type: number
          description: The size of artifact in kb
        name:
          type: string
          description: The name of artifact
        path:
          type: string
          description: The path to artifact
        fileType:
          type: string
          enum:
            - CSV
            - JSON
            - PDF
            - PNG
            - LAS
            - ENTWINE
            - ZIP
            - LOG
          description: The file type of artifact
      example:
        id: 123
        simulationId: 123
        stepId: 11
        createdUtc: 123124124
        sizeKb: 120
        path:  /home/user/dev/simbad/data/SIM_0_CONF_parametric_evolution_3d/cli_out.csv
    SimulationStepInfo:
      type: object
      required:
        - id
        - status
        - simulationId
        - startedUtc
        - origin
        - celeryId
      properties:
        id:
          type: number
          description: The id of step
        status:
          type: string
          enum:
            - 'ONGOING'
            - 'SUCCESS'
            - 'FAILURE'
        simulationId:
          type: number
          description: The id of simulation in which the step was executed
        startedUtc:
          type: string
          description: UTC timestamp when step was started
        finishedUtc:
          type: string
          description: UTC timestamp when step was finished
        origin:
          type: string
          enum:
            - CONF
            - CLI
            - ANALYZER
            - REPORT
          description: Step origin
        celeryId:
          type: string
          description: The celery task id of given step
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactInfo'
        cliRuntimeInfo:
          type: object
          $ref: "#/components/schemas/CliRuntimeInfo"
        analyzerRuntimeInfo:
          type: object
          $ref: "#/components/schemas/AnalyzerRuntimeInfo"
      example:
        id: 123
        simulationId: 123
        stepId: 11
        createdUtc: 123124124
        sizeKb: 120
        path:  /home/user/dev/simbad/data/SIM_0_CONF_parametric_evolution_3d/cli_out.csv
    SimulationInfo:
      type: object
      required:
        - id
        - status
        - startedUtc
        - currentStepId
        - workdir
        - steps
        - artifacts
      properties:
        id:
          type: number
          description: The id of simulation
        startedUtc:
          type: string
          description: UTC timestamp when simulation was started
        finishedUtc:
          type: string
          description: UTC timestamp when simulation was finished
        currentStepId:
          type: number
          description: Id of currently excuted step
        status:
          type: string
          description: The status of simulation step
          enum:
            - 'ONGOING'
            - 'SUCCESS'
            - 'FAILURE'
        workdir:
          type: string
          description: The path to working directory for this simulation
        steps:
          type: array
          items:
            $ref: '#/components/schemas/SimulationStepInfo'
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactInfo'
        cliRuntimeInfo:
          type: object
          $ref: "#/components/schemas/CliRuntimeInfo"
        analyzerRuntimeInfo:
          type: object
          $ref: "#/components/schemas/AnalyzerRuntimeInfo"
    CliRuntimeInfo:
      type: object
      required:
        - cpu
        - memory
        - progress
      properties:
        cpu:
          type: number
          description: Cli cpu usage in percent
        memory:
          type: number
          description: Cli memory usage in megabytes
        progress:
          type: number
          description: Cli command progress
        error:
          type: string
          description: Error message
    AnalyzerRuntimeInfo:
      type: object
      required:
        - progress
      properties:
        sparkJobId:
          type: number
          description: Id of spark job
        progress:
          type: number
          description: The progress of job
        error:
          type: string
          description: Error message
    SimulationRangeRequest:
      type: object
      properties:
        id:
          type: number
          description: The id of simulation
        num:
          type: number
          description: The number of simulations after id to return
    SimpleRuntimeInfo:
      type: object
      required:
        - status
        - progress
      properties:
        progress:
          type: number
          description: Simulation step progress
        status:
          type: string
          description: The status of simulation step
          enum:
            - 'ONGOING'
            - 'SUCCESS'
            - 'FAILURE'
    ConfigurationInfo:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
          description: The name of the configuration
        id:
          type: number
          description: The id of the configuration
    SimulationSimpleInfo:
      type: object
      required:
        - simulationId
        - configuration
        - startedUtc
        - status
      properties:
        simulationId:
          type: number
          description: The id of the simulation
        status:
          type: string
          description: The status of simulation
          enum:
            - 'ONGOING'
            - 'SUCCESS'
            - 'FAILURE'
        startedUtc:
          type: string
          description: UTC timestamp when step was started
        finishedUtc:
          type: string
          description: UTC timestamp when step was finished
        reportId:
          type: number
          description: The id of simulation report
        configuration:
          type: object
          $ref: "#/components/schemas/ConfigurationInfo"
        cli:
          type: object
          $ref: "#/components/schemas/SimpleRuntimeInfo"
        analyzer:
          type: object
          $ref: "#/components/schemas/SimpleRuntimeInfo"
        reports:
          type: object
          $ref: "#/components/schemas/SimpleRuntimeInfo"

